### ISSUE TITLE
OAuth 참고자료

### ISSUE THREAD

**Issue by joks1997** [swpp-team1/c-vs#12]
https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html
http://hyunalee.tistory.com/8

**Comment by joks1997** [comment]
https://dodo4513.github.io/2017/02/12/facebook_oauth/

**Comment by joks1997** [comment]
https://github.com/RealmTeam/django-rest-framework-social-oauth2
이거다 미친

**Comment by joks1997** [comment]
위에거에 올린 모듈 deprecated됨...

https://github.com/keppelen/react-facebook-login/blob/master/README.md
https://beomi.github.io/2017/02/08/Setup-SocialAuth-for-Django/
https://blog.hyeungshikjung.com/django-rest-fb-token/
https://github.com/vinitraj10/Django-React-Blog

**Comment by joks1997** [comment]
http://whatisthenext.tistory.com/129

**Comment by joks1997** [comment]
http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html

**Comment by joks1997** [comment]
페이스북 로그인은 https 서버를 필요로함

**Comment by kev-damian** [comment]
OAuth 사용하지않기로 결론냈으므로 Close 하겠음
