### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Yeonduru** [swpp-team1/c-vs#17]
Backend 궁금한점

- Comment 모델에만 rating field가 있는데 Recipe랑 Product에 대한 점수매기기(?)는 항상 코멘트에만 포함되어서 가는건지..?
- 그리고 rating 가성비 등등으로 세분화 하기로 한건 어떻게 됐었나요..?

**Comment by kev-damian** [comment]
Rating은 우선 전반적인 만족도만 조사하는게 좋을것 같아서 그렇게 디자인 했구
Rating Field는 Review에서도 가능해야함!

**Comment by 9Hyeonwoo** [comment]
- 생각해보니 Rating Model 을 하나 만들어서 Foreign Key로 하는게 좋겠다
- 세분화는 석현아 말대로 입니다
