### ISSUE TITLE
인기 제품(상품), 인기 레시피 알고리즘 

### ISSUE THREAD

**Issue by kev-damian** [swpp-team1/c-vs#25]
지금 생각하고 있는건

각 분류항목별로 각 회사에서 가장 평점이 높은 제품들 목록을 구성한 뒤

랜덤으로 3개씩 불러서 메인화면에 띄워주는거 생각중입니다.

더 좋은 의견 있으시면 코멘트 남겨주세요

**Comment by joks1997** [comment]
회사별로 평점 탑 텐 정해서 띄우기? 그게 아니라면 탑 텐 중에 몇개씩 골라서 띄우기

**Comment by kev-damian** [comment]
평점순으로 띄우고, 평점같은경우 평점참여횟수로 정렬
